export default {
    columnNames: '[class="element-group"]:has(span:contains("Interactions")) ul>li>span',
    listOfElements: '[id="demo-tabpane-list"]>div>div',
    gridOfElements: '[id="demo-tabpane-grid"] .list-group-item',
    tabGridElems: '[id="demo-tab-grid"]',
    selectList: '[id="verticalListContainer"]>li',
    resizableBoxWithRestrict: '[id="resizableBoxWithRestriction"]',
    resizeableRestrictedHandler: '#resizableBoxWithRestriction .react-resizable-handle',
    resizableUnlimBoxHandler: '#resizable .react-resizable-handle',
    draggable: '#draggable',
    droppable: '#droppable',
    acceptTabInDroppable: '[id="droppableExample-tab-accept"]',
    notAcceptable: '#notAcceptable',
    acceptable: '#acceptable',
    acceptDroppable: '[id="droppableExample-tabpane-accept"] [id="droppable"]',
    propogationTab: '[id="droppableExample-tab-preventPropogation"]',
    dragBox: '#dragBox',
    notGreedyDropBoxPropogation: '#notGreedyDropBox',
    notGreedyInnerDropBoxPropogation: '#notGreedyInnerDropBox',
    greedyDropBoxPropogation: '#greedyDropBox',
    greedyDropBoxInnerPropogation: '#greedyDropBoxInner',
    revertTab: '#droppableExample-tab-revertable',
    revertableBox: '#revertable',
    nonrevertableBox: '#notRevertable',
    revertDropBox: '[id="droppableExample-tabpane-revertable"] [id="droppable"]',
    tabAxisRestrict: '#draggableExample-tab-axisRestriction',
    restrictedX: '#restrictedX',
    restrictedY: '#restrictedY',

}