export default {
    columnNames: '[class="element-group"]:has(span:contains("Widgets")) ul>li>span',
    accordions: '.accordion',
    lastColorInMultipleForm: '[id="autoCompleteMultipleContainer"] [class$=auto-complete__multi-value]',
    inputMultipleColors: '[id="autoCompleteMultipleContainer"]',
    inputSingleColor: '[id="autoCompleteSingleContainer"]',
    resultInSingleColorField: '[id="autoCompleteSingle"] [class^="auto-complete__single-value"]',
    dateInput: '[id="datePickerMonthYearInput"]',
    dateTimeInput: '[id="dateAndTimePickerInput"]',
    datePickerMonthSelectInCalendar: '.react-datepicker__month-select',
    datePickerYearSelectInCalendar: '.react-datepicker__year-select',
    datePickerDayInCurrentMonth: 'div[aria-disabled="false"]:not(.react-datepicker__day--outside-month)',
    datePickerTimeInCalendar: '.react-datepicker__time-list',
    datePickerYear: '.react-datepicker__year-read-view',
    datePickerYearDropDown: '.react-datepicker__year-dropdown',
    datePickerMonth: '.react-datepicker__month-read-view',
    datePickerMonthDropDown: '.react-datepicker__month-dropdown',
    sliderContainer: '[id="sliderContainer"] input[type="range"]',
    sliderValue: '[id="sliderValue"]',
    startStopButton: '[id="startStopButton"]',
    progressBar: '[role="progressbar"]',
    tabsList: '[role="tablist"]',
    toolTipBtn: '[id="toolTipButton"]',
    toolTipTextField: '[id="texFieldToolTopContainer"]',
    addressLinkHower: 'a:contains("1.10.32")',
    contraryLinkHower: 'a:contains("Contrary")',
    listsInMenu: '[id="nav"] [href="#"]',
    dropDownOptionsWithGroup: '[id="withOptGroup"]',
    dropDownOptionsOne: '[id="selectOne"]',
    selectOldStyle: '[id="oldSelectMenu"]',
    dropDownMenu: '[class $="menu"]',
    multiSelectField: '[id="react-select-10-input"]',
    standartSelector: '[id="cars"]',
    multiValue: '[class$="multiValue"]',
    option: '[class$="option"]'    
}