name: mochaReportAndSplit
on:
  schedule:
    - cron: 0 18 * * 1-5
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test tags (UI, e2e, regression, smoke, API)'
        required: false
        default: 'regression'
        type: string
jobs:
  merge-reports:
    uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v2
    with:
      nE2E: 3
      # start: npx cypress run --browser chrome
      command: npx cypress run --browser chrome --env grepTags="${{github.event.inputs.tags || 'regression'}}"
      # merge all test reports into one
      # https://github.com/bahmutov/cypress-workflows
      marge: true