name: parallelRegress
on:
  schedule:
    - cron: 0 1 * * 1-5
  workflow_dispatch: null
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - name: Create matrix ⊹
        id: prepare
        uses: bahmutov/gh-build-matrix@main
        with:
          n: 3 # number of containers to output

      - name: Print result 🖨
        run: echo '${{ steps.prepare.outputs.matrix }}'

  test-split:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Print GitHub strategy context 🖨
        run: echo '${{ toJSON(strategy) }}'

      - name: Run split Cypress tests 🧪
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser chrome
          publish-summary: false
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
  
  upload-artifact:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Upload reports
        uses: actions/upload-artifact@v4        
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos
            cypress/results
          if-no-files-found: ignore