name: parallelRegressStage
on:
  schedule:
    - cron: 0 1 * * 1-5
  workflow_dispatch: null
jobs:
  jobs: null
  test-split:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers:
          - 1
          - 2
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
      - name: Run split Cypress tests
        uses: cypress-io/github-action@v6
        with:
          publish-summary: false
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
