# Define the manual-test-run workflow
name: parallelRegressStage
on:
  schedule:    
    - cron: '0 1 * * 1-5'
    # Запускает в минуты :00, часы 18Z+00, каждые day, каждые month, в Пн, Вт, Ср, Чт, Пт.
  workflow_dispatch:     

jobs:
  test-split:
    runs-on: ubuntu-latest
    # use two containers to run the tests
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: debug
        run: |
          printenv
          whereis npm

      - name: Run Tests
        run: npm run test

      - name: Run split Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # we don't need Cypress own runner summary
          publish-summary: false
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}